cargo-features=["strip"]

[package]
name = "qr-native"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[profile.release]
panic = "abort"
codegen-units = 1
lto = true
#opt-level = 3
opt-level = "z"
debug = false
incremental = false

strip = "symbols"


[lib]
name = "qrnative"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
bindgen = "0.57.0"
cmake = "0.1.44"
cc = "1.0.56"

[dependencies]
qrcode = "0.12.0"
image = { version = "0.23.14" }
css-color-parser = "0.1.2"



[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.10.1"
log = "0.4.14"

[target.'cfg(target_os="ios")'.dependencies]
